### ISSUE TITLE
How is it different than Leshan?

### ISSUE THREAD

**Issue by nginxsantos** [PeterEB/coap-shepherd#8]
Hi,
Could you please clarify the benefits of this project over Leshan?

Thanks,Santos

**Comment by Falinor** [comment]
Hey,

I am not a maintainer of this project, just a user. And as I see, if I don't get it wrong,
Eclipse Leshan is a LWM2M implementation in Java.
So I believe the project coap-shepherd is just an implementation in Node.js.

**Comment by PeterEB** [comment]
Hi @nginxsantos,

As @Falinor mentioned, coap-shepherd is an implementation in Node.js. I am current running another project of a bootstrap server just like Leshan.

**Comment by myusri** [comment]
Hi @PeterEB ,
Care to elaborate a bit on your lwM2M bootstrap server project? Thanks.

**Comment by PeterEB** [comment]
Hi @myusri ,

Bootstrap server implementation delay for some time, since I was a little busy some time ago.
I will implement bootstrap server recently. 

I'll let you know when update comes up.

**Comment by PeterEB** [comment]
Hi @myusri, 

I implement a Bootstrap Server [**lwm2m-bs-server**](https://github.com/PeterEB/lwm2m-bs-server). And **coap-shepherd** and **coap-node** have new version. 

**lwm2m-bs-server** is a Bootstrap Server. It can configures client bootstrap information and configures the LwM2M Client.

In the latest version **coap-node**, it support mulitple servers, factory bootstrap and client initiated bootstrap. 

If you have any question or suggestion, please let me know. Thacks!
