### ISSUE TITLE
setIncomingDevPredicate deprecated

### ISSUE THREAD

**Issue by ghost** [PeterEB/coap-shepherd#9]
Greetings, you've updated setIncomingDevPredicate to acceptDevIncoming method in this [commit](https://github.com/PeterEB/coap-shepherd/commit/5451b2ec35403a851e64df9b89a846047b77b78e).
I'd be really grateful if you updated the wiki on the new usage. 
Because currently, as it is, I'm experiencing the following error:
![2018-02-18 15 41 00](https://user-images.githubusercontent.com/8872649/36351365-3b3ed068-14c2-11e8-8033-83864d8715c5.png)

**Comment by PeterEB** [comment]
Hi @exSpectrum, I add API `acceptDevIncoming()` in version 0.2.9. And update the [usage](https://github.com/PeterEB/coap-shepherd/wiki#cserveracceptdevincomingpredicate) in the wiki.
If you have time, you could test it to see if it behave better now.

**Comment by ghost** [comment]
Thanks!
I really appreciate your feedback. Will test is asap.
